Feedback
spbu-coding/1-st085683 pull request #1
Opened 2020-10-02 12:08 UTC by EgorkaKulikov

:wave:! GitHub Classroom created this pull request as a place for your teacher to leave feedback on your work. It will update automatically. **Don’t close or merge this pull request**, unless you’re instructed to do so by your teacher.

In this pull request, your teacher can leave comments and feedback on your code. Click the **Subscribe** button to be notified if that happens.

Click the **Files changed** or **Commits** tab to see all of the changes pushed to `master` since the assignment started. Your teacher can see this too.

<details>
<summary>
<strong>Notes for teachers</strong>
</summary>

Use this PR to leave feedback. Here are some tips:

- Click the **Files changed** tab to see all of the changes pushed to `master` since the assignment started. To leave comments on specific lines of code, put your cursor over a line of code and click the blue **+** (plus sign). To learn more about comments, read “[Commenting on a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request)”.
- Click the **Commits** tab to see the commits pushed to `master`. Click a commit to see specific changes.
- If you turned on autograding, then click the **Checks** tab to see the results.
- This page is an overview. It shows commits, line comments, and general comments. You can leave a general comment below.

For more information about this pull request, read “[Leaving assignment feedback in GitHub](https://classroom.github.com/help/leaving-feedback-in-github)”.
</details>

2020-10-13 20:52 UTC, merged

2020-10-14 12:48 UTC, st085683 requested changes
Здравствуйте! Вот она:

2020-10-15 16:18 UTC, EgorkaKulikov commented on [WIP]main(st085683).c
> +#ifndef M_PI
По идее, в таком ifndef не должно быть необходимости, но формально он более-менее корректен

2020-10-15 16:18 UTC, EgorkaKulikov commented on [WIP]main(st085683).c
> +#include <math.h>
[WIP] имеет смысл писать в имени пулреквеста, но не файла.

2020-10-15 16:18 UTC, EgorkaKulikov commented on [WIP]main(st085683).c
> +double rect_method(double left_b, double right_b)
как правило, в названии метода рекомендуют использовать глагол, отражающий, что метод делает

2020-10-15 16:18 UTC, EgorkaKulikov commented on [WIP]main(st085683).c
> +void results(char** res, int count)
это метод освобождения памяти, название results странное

2020-10-15 16:18 UTC, EgorkaKulikov commented on [WIP]main(st085683).c
> +    struct interval_x int_val = { 0, 0 };
А зачем здесь инициализация нулями? Если уже в следующей команде мы считываем реальное значение?

2020-10-15 16:18 UTC, EgorkaKulikov commented on [WIP]main(st085683).c
> +	char** ending = calculation_of_integration(int_val, part, test_c);
имя переменно странное: про какое окончание идёт речь?

2020-10-15 16:18 UTC, EgorkaKulikov commented on [WIP]main(st085683).c
> +	char** rslts = (char**)malloc(sizeof(char*) * test_c);
функция malloc потенциальна могла вернуть код ошибки, точно так же, как и printf, например

2020-10-15 16:18 UTC, EgorkaKulikov commented
Поскольку задача сдана более чем через 10 дней после дедлайна, -5 баллов. За остальное не снижаю.
Оценка 5 из 10

2020-10-15 16:21 UTC, st085683 commented on [WIP]main(st085683).c
> +#ifndef M_PI
Понял.

2020-10-15 16:24 UTC, st085683 commented on [WIP]main(st085683).c
> +void results(char** res, int count)
Да)

2020-10-15 16:33 UTC, st085683 commented
Благодарю вас! 
Я выполню  ваши замечания.